@echo off
REM Generated by scripts/sync_check_env.py. Do not edit manually.

setlocal
set "PYTHONUTF8=1"
set "PY="

REM Prefer the normal Windows python entry first. Only use python3 if it
REM actually runs Python 3.10+, because python3.exe can be a broken alias.
python -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" >nul 2>&1
if not errorlevel 1 set "PY=python"

if not defined PY (
    py -3 -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" >nul 2>&1
    if not errorlevel 1 set "PY=py -3"
)

if not defined PY (
    python3 -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" >nul 2>&1
    if not errorlevel 1 set "PY=python3"
)

if not defined PY (
    echo Python 3.10+ not found. Install Python first.
    exit /b 1
)

%PY% "%~dp0check_env.py"
exit /b %errorlevel%
