#!/bin/sh
# Generated by scripts/sync_check_env.py. Do not edit manually.

set -eu
export PYTHONUTF8=1

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PY=""

if python3 -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" >/dev/null 2>&1; then
  PY=python3
elif python -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" >/dev/null 2>&1; then
  PY=python
fi

if [ -z "$PY" ]; then
  echo "Python 3.10+ not found. Install Python first."
  exit 1
fi

exec "$PY" "$SCRIPT_DIR/check_env.py"
