#!/usr/bin/env python3
# Generated by scripts/sync_check_env.py. Do not edit manually.
from __future__ import annotations

import importlib
import importlib.metadata
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


MIN_PYTHON = (3, 10)

IMPORT_NAME_OVERRIDES = {
    "opencv-python": "cv2",
    "pillow": "PIL",
    "scikit-image": "skimage",
}

try:
    # 标准接口,完整覆盖 PEP 508(==/~=/!=/<=/extras/environment markers)。
    # packaging 是 pip 自身的依赖,几乎总是可用;缺失时退化到下方手写解析。
    from packaging.requirements import Requirement as _PkgRequirement
    _HAS_PACKAGING = True
except ImportError:  # 极少数无 packaging 的环境
    _HAS_PACKAGING = False

# 手写 fallback 只比较这些算子;~= / === / != 无法可靠比较,退化为"仅校验能否 import"。
_FALLBACK_NAME = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?\s*(?P<specs>.*)$")
_FALLBACK_SPEC = re.compile(r"(>=|<=|==|>|<)\s*([0-9][0-9A-Za-z.\-+_]*)")


@dataclass(frozen=True)
class Requirement:
    pip_spec: str
    dist_name: str
    import_name: str
    specifier: object = None      # packaging SpecifierSet,或 None(走 fallback)
    marker: object = None         # packaging Marker,或 None
    fallback: tuple = ()          # ((op, version_tuple), ...),无 packaging 时使用


def configure_output() -> None:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")


def parse_version(value: str) -> tuple[int, ...]:
    parts: list[int] = []
    for raw in re.split(r"[.\-+_]", value):
        match = re.match(r"\d+", raw)
        if match:
            parts.append(int(match.group(0)))
        elif parts:
            break
    return tuple(parts)


def _import_name_for(dist_name: str) -> str:
    return IMPORT_NAME_OVERRIDES.get(dist_name.lower(), dist_name.replace("-", "_"))


def _cmp(actual: tuple[int, ...], target: tuple[int, ...]) -> int:
    width = max(len(actual), len(target))
    a = actual + (0,) * (width - len(actual))
    b = target + (0,) * (width - len(target))
    return (a > b) - (a < b)


def requirement_applies(requirement: Requirement) -> bool:
    """环境 marker 评估:不适用于当前环境的依赖直接跳过(仅 packaging 路径)。"""
    if requirement.marker is None:
        return True
    try:
        return bool(requirement.marker.evaluate())
    except Exception:
        return True


def version_satisfied(requirement: Requirement, version: str) -> bool:
    if requirement.specifier is not None:
        return requirement.specifier.contains(version, prereleases=True)
    actual = parse_version(version)
    ops = {">=": lambda c: c >= 0, ">": lambda c: c > 0,
           "<=": lambda c: c <= 0, "<": lambda c: c < 0,
           "==": lambda c: c == 0}
    for op, target in requirement.fallback:
        if not ops[op](_cmp(actual, target)):
            return False
    return True


def parse_requirement(line: str) -> Requirement | None:
    stripped = line.split("#", 1)[0].strip()
    if not stripped:
        return None

    if _HAS_PACKAGING:
        req = _PkgRequirement(stripped)
        return Requirement(
            pip_spec=stripped,
            dist_name=req.name,
            import_name=_import_name_for(req.name),
            specifier=req.specifier,
            marker=req.marker,
        )

    # fallback:解析名字 + 可比较的算子;markers(`;` 之后)无法评估,忽略后照常检查。
    name_match = _FALLBACK_NAME.match(stripped.split(";", 1)[0].strip())
    if not name_match:
        raise ValueError(f"Unsupported requirement format: {line}")
    dist_name = name_match.group("name")
    constraints = tuple(
        (op, parse_version(ver))
        for op, ver in _FALLBACK_SPEC.findall(name_match.group("specs")))
    return Requirement(
        pip_spec=stripped,
        dist_name=dist_name,
        import_name=_import_name_for(dist_name),
        fallback=constraints,
    )


def read_requirements(path: Path) -> list[Requirement]:
    requirements: list[Requirement] = []
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        requirement = parse_requirement(line)
        if requirement is not None:
            requirements.append(requirement)
    return requirements


def check_python_version() -> bool:
    if sys.version_info >= MIN_PYTHON:
        return True

    required = ".".join(map(str, MIN_PYTHON))
    actual = ".".join(map(str, sys.version_info[:3]))
    print(f"ERROR Python {required}+ required, got {actual}.")
    return False


def check_missing(requirements: list[Requirement]) -> list[Requirement]:
    missing: list[Requirement] = []
    for requirement in requirements:
        if not requirement_applies(requirement):
            print(f"  SKIP {requirement.dist_name} (marker not applicable)")
            continue
        try:
            version = importlib.metadata.version(requirement.dist_name)
            importlib.import_module(requirement.import_name)
        except (importlib.metadata.PackageNotFoundError, ImportError):
            missing.append(requirement)
            print(f"  MISSING {requirement.pip_spec}")
            continue

        if not version_satisfied(requirement, version):
            missing.append(requirement)
            print(f"  OUTDATED {requirement.dist_name} {version} (needs {requirement.pip_spec})")
            continue

        print(f"  OK {requirement.dist_name} {version}")
    return missing


def install_missing(missing: list[Requirement]) -> bool:
    if not missing:
        print("\nAll dependencies ready.")
        return True

    pip_specs = [item.pip_spec for item in missing]
    command = [sys.executable, "-m", "pip", "install", *pip_specs]
    print("\nInstalling missing dependencies: " + " ".join(pip_specs))
    result = subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )

    if result.returncode != 0:
        print("\npip install failed.")
        tail = (result.stderr or result.stdout)[-1200:]
        if tail:
            print(tail)
        print("\nTry manually: " + " ".join(command))
        return False

    print("\nVerifying installed dependencies...")
    return True


def main() -> int:
    configure_output()
    print(f"Python: {sys.executable} ({sys.version.split()[0]})")
    if not check_python_version():
        return 1

    requirements_path = Path(__file__).with_name("requirements.txt")
    if not requirements_path.exists():
        print(f"ERROR requirements file not found: {requirements_path}")
        return 1

    print(f"Requirements: {requirements_path}")
    print("Checking dependencies...\n")

    requirements = read_requirements(requirements_path)
    missing = check_missing(requirements)
    if not install_missing(missing):
        return 1

    if missing:
        missing_after_install = check_missing(requirements)
        if missing_after_install:
            print("\nSome dependencies are still missing.")
            return 1
        print("\nAll dependencies ready.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
